name: ImagetoBlockPlugin
version: ${project.version}
main: visar.plugins.ImagetoBlockPlugin.Main
api-version: 1.16
commands:
  image:
    description: generates image
    #usage: /image [URL or File Path] [width] [height]
  setdefaultimage:
    description: sets default image to preferred image
    #usage: /setdefaultimage <URL or File Path>
  video:
    description: generates video
    #usage: /video [File Path] [width] [height]
  setdefaultvideo:
    description: sets default video
    #usage: /setdefaultvideo <File Path>
  vertical:
    description: sets if picture should be vertically or horizontally
  togglevertwarning:
    description: sets if warning should be displayed or not
  canvas:
    description: creates canvas
  delcanvas:
    description: deletes canvas
  cimage:
    description: canvas displays image
  cvideo:
    description: canvas displays video
  clearcanvas:
    description: clears canvas

